# Generated by Django 3.2.6 on 2021-08-19 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KanRezec',
            new_name='IntGroove',
        ),
    ]
