# Generated by Django 3.2.5 on 2021-08-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KanRezec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dmin', models.DecimalField(decimal_places=1, max_digits=1000)),
                ('ap', models.DecimalField(decimal_places=1, max_digits=1000)),
                ('h', models.DecimalField(decimal_places=1, max_digits=1000)),
                ('r', models.DecimalField(decimal_places=1, max_digits=1000)),
                ('Lmax', models.DecimalField(decimal_places=1, max_digits=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RastRezec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dmin', models.DecimalField(decimal_places=1, max_digits=1000)),
                ('ap', models.DecimalField(decimal_places=1, max_digits=1000)),
                ('gugol', models.DecimalField(decimal_places=1, max_digits=1000)),
                ('ugol', models.DecimalField(decimal_places=1, max_digits=1000)),
                ('Lmax', models.DecimalField(decimal_places=1, max_digits=1000)),
            ],
        ),
    ]
